# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Armor5Games
email: armor5games@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
version: 0.0.4
permalink: /:categories/:title/

navigation:
  ru:
  - name: Главная
    url: /ru/
    layout: home
  - name: Игры
    url: /ru/games/
    submenu:
    - name: Rise of Pirates
      url: /ru/games/rise-of-pirates
  - name: О нас
    url: /ru/about/
    submenu:
    - name: Команда
      url: /ru/about/team/
  - name: Вакансии
    url: /ru/careers/
  - name: Контакты
    url: /ru/contacts/
  en:
  - name: Home
    url: /
    layout: home
  - name: Games
    url: /en/games/
    submenu:
    - name: Rise of Pirates
      url: /en/games/rise-of-pirates
  - name: About us
    url: /en/about/
    submenu:
    - name: Team
      url: /en/about/team/
  - name: Careers
    url: /en/careers/
  - name: Contacts
    url: /en/contacts/
